services:
  api:
    build:
      context: .
      target: dev
    ports:
      - 8000:8000
    volumes:
      - .:/app
    environment:
      BACKEND_NAME: ${BACKEND_NAME:-stapi_fastapi_landsat:LandsatBackend}
