name: Deploy demo to AWS

on:
  workflow_dispatch:
    inputs:
      image_tag_or_digest:
        description: docker image tag or digest to deploy
        required: true
        default: latest
        type: string
      backend_name:
        description: backend to use (blacksky, umbra, up42 or landsat)
        required: false
        default: landsat
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry==1.7.1
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: poetry
      - name: Install deploy dependencies
        run: poetry install --only=deploy-aws
      - name: Run CDK deploy
        uses: ./.github/actions/cdk-deploy
        with:
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_ACCESS_KEY_ID: ${{ vars.AWS_ACCESS_KEY_ID }}
          AWS_ECR_REPOSITORY_ARN: ${{ vars.AWS_ECR_REPOSITORY_ARN }}
          IMAGE_TAG_OR_DIGEST: ${{ inputs.image_tag_or_digest }}
          BACKEND_NAME: ${{ inputs.backend_name }}
